export const FETCH_SEASONS_ERROR = "FETCH_SEASONS_ERROR";
export const FETCH_SEASONS_SUCCESS = "FETCH_SEASONS_SUCCESS";
export const FETCH_TABLE_SEASON = "FETCH_TABLE_SEASON";
export const FETCH_PLAYERS_BY_POSITION = "FETCH_PLAYERS_BY_POSITION";
